### ISSUE TITLE
Data worden foutief weergegeven in 'nieuws'

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#100]
Een correct ingevulde datum in het veld 'agendadatum' wordt bij opslaan van het bericht verkeerd bewaard.
De dag wordt correct weergegeven, maar maand en jaar lijken steeds te worden gewijzigd in augustus 2019.

**Comment by eeemarv** [comment]
Ok, ik bekijk het

**Comment by eeemarv** [comment]
Het zou opgelost moeten zijn. Bedankt om te melden!
