### ISSUE TITLE
andere mailservice dan Mandrill

### ISSUE THREAD

**Issue by marttiphpbb** [eeemarv/eland#13]
Omdat Mandrill nu geen gratis plan meer heeft (begint nu vanaf $9,95/maand), zou ook minstens één andere mailservice ondersteund moeten worden.

**Comment by eeemarv** [comment]
AWS SES geeft 62000 gratis emails per maand maar elke verzender moet apart geverifiëerd worden, dus dat is geen optie.

**Comment by dimitrydhondt** [comment]
Ouch, Is die $120/jaar een probleem qua financiering op dit moment ?
Is de implementatie in eLAND via SMTP op de Mandrill specifieke API ? SMTP lijkt de beste optie qua compatibiliteit.

De andere grote speler naast Mandrill is Sendgrid. Momenteel krijg je daar wel 12000 mails/maand gratis. Als ik me niet vergis kan je met SMTP ook over sendgrid sturen.

**Comment by eeemarv** [comment]
Momenteel gebruikt eLAND nog de php-client voor Mandrill. Maar het zou inderdaad beter zijn over te schakelen naar SMTP. De php-client bevat wel specifieke templating voor bulk mail. Dit zou dan zelf geïmplementeerd moeten worden (elke mail apart verzenden). Niet zo'n probleem waarschijnlijk.

**Comment by eeemarv** [comment]
Eind april wordt Mandrill definitief betalend, nl. minstens 25 dollar per maand en per blok van 25000 mails. Ondertussen is eLAND herwerkt om emails per SMTP te versturen. Ik wacht nog op goedkeuring van Amazon SES om de Sandbox mode op te heffen. SES kost $0.10 per 1000 mails. Mijn eerdere opmerking dat je 62000 mails gratis krijgt, klopt niet. Dit is enkel als je ook een EC2 afneemt bij Amazon.
