### ISSUE TITLE
Onduidelijkheid maximale bestandsgrootte foto's

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#146]
De voorbije weken hebben meerdere van onze leden problemen met het uploaden van foto's, met de melding dat de foto te groot is.  Nadat ik hun foto verklein lukt het probleemloos.
Na een paar testjes merk ik, dat foto's van ruim 6 MB geen problemen geven, terwijl andere foto's met slechts de halve bestandsgrootte geweigerd worden.  Graag duidelijkheid over de maximale grootte.

**Comment by eeemarv** [comment]
De maximale grootte aan serverkant-ontvangst was 200k. Ik heb het nu verdubbeld naar 400k.
De foto's worden aan in de Client met Javascript verkleint alvorens op te laden, behalve in smartphones, want die doen dat (normaal gezien) zelf. Het kan zijn dat de laatste tijd  smartphones grotere bestanden doorsturen, daarmee dat de 200k limiet bereikt werd. Aan serverkant wordt de foto ook nog eens verkleind.
