### ISSUE TITLE
Probleem bij massa-transacties

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#166]
Bij poging tot uitvoeren van een massa-transactie krijg ik een foutmelding

**Comment by eeemarv** [comment]
Wat is de foutmelding dan?

**Comment by AnneTanne** [comment]
Ik vermoed dat het een tijdelijke glitch was... Ik kreeg een melding in de zin van 'deze pagina werkt niet', maar intussen lukt het me terug; ook vanuit een ander account dat het doel)account.

**Comment by eeemarv** [comment]
Mja, er was vanmorgen een kleine complicatie met het updaten van software (Dokku) op de server waardoor requests waarschijnlijk naar het verkeerde (oudere) proces 'ge-route" werden. Er ontbreken ook logs zoals je kan zien van 6u51 tot 12u48. Voor de logs werd geluisterd naar de nieuwe container/proces terwijl requests naar de oudere container/proces gestuurd werden. Inmiddels is de update goed verlopen, maar zijn er nog "zombie-docker-containers" die niet gedelete geraken (dit zal wel opgelost geraken maar het zou geen invloed mogen hebben). Dus misschien heeft het hier mee te maken, maar zonder logs valt er niet veel over te zeggen.
