### ISSUE TITLE
Foutmelding bij massa-transacties

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#198]
Bij aanklikken van 'Massa-transacties' onder het tandwiel op de pagina 'transacties' krijg ik een 500 pagina met volgende melding:
Argument 4 passed to App\Render\LinkRender::link_no_attr() must be of the type string, null given, called in /app/src/Controller/MassTransactionController.php on line 849

(LETS Zandland)

**Comment by eeemarv** [comment]
Ok ik zie wat de fout is. Ik probeer er vanavond naar te kijken.

**Comment by eeemarv** [comment]
Het zou nu opgelost moeten zijn.

**Comment by AnneTanne** [comment]
Dankjewel!

Vriendelijke groeten,
Ann


mailto:ann.van.roy@annetanne.be
http://annetanne.be
