### ISSUE TITLE
Zichtbaarheid inactieve leden

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#230]
Wanneer ik de gedesactiveerde leden wil bekijken, krijg ik volgende foutmelding:
500
Argument 4 passed to App\Render\LinkRender::link_no_attr() must be of the type string, null given, called in /app/src/Controller/UsersListController.php on line 1472

**Comment by eeemarv** [comment]
Ok, een fix is onderweg

**Comment by eeemarv** [comment]
't Is gefixt.

**Comment by eeemarv** [comment]
Dit werd veroorzaakt doordat we nu NULL (lege) waarden toelaten voor de volledige naam in de database en de functie in de foutmelding was daar nog niet voor aangepast. Account LM165 bevat een lege volledige naam.

**Comment by AnneTanne** [comment]
Fantastisch, dankjewel!
