### ISSUE TITLE
Toevoegen bijkomende contacten

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#236]
Bij een poging een tweede e-mail adres toe te voegen aan de contact-informatie volgende foutmelding:
500
Unable to generate a URL for the named route "status" as such route does not exist.

**Comment by eeemarv** [comment]
Ok, dank u. Ik bekijk het vandaag.

**Comment by eeemarv** [comment]
Het zou nu opgelost moeten zijn. Specifiek trad deze fout op wanneer de gebruiker een identiek email adres heeft dan een andere gebruiker (en dus niet kan inloggen met e-mail adres). Dan wordt steeds een waarschuwing weergegeven. De waarschuwing bevatte nog een link naar de "status" pagina, die niet meer bestaat.

**Comment by eeemarv** [comment]
Edit: over 5 minuten staat de nieuwe code online.
