### ISSUE TITLE
Foutmelding bij poging tot navigeren naar user-account

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#241]
Wanneer ik in eLAND onder Users om het even welk  gebruikersaccount aanklik (via code of via naam), krijg ik volgende foutmelding:
500
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("id") to generate a URL for route "users_show".").

(Overigens kreeg een van onze leden recent bij het uitvoeren van transacties volgende foutmelding:
500
Call to a member function insert() on null

(Overigens werden de transacties correct uitgevoerd, maar ze kreeg er zelf geen bevestiging van).  Ik heb dit niet kunnen reproduceren.

**Comment by AnneTanne** [comment]
Bij het toevoegen van een nieuw lid krijg ik een identieke foutmelding als hierboven.
Het lid wordt wel correct toegevoegd.

500
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("id") to generate a URL for route "users_show".").

**Comment by AnneTanne** [comment]
(foutje....)

**Comment by eeemarv** [comment]
Inderdaad, dat komt door een bug in nieuwe code die net opgeladen is en ik heb de fout ook opgemerkt en gecorrigeerd. De fix staat seffens online. Dank u!

**Comment by eeemarv** [comment]
Ok, klaar.

**Comment by AnneTanne** [comment]
Heel erg bedankt!

Vriendelijke groeten,
Ann


***@***.***
http://annetanne.be
