### ISSUE TITLE
Foutmelding bij invoeren van transactie, geen bevestiging per mail

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#243]
Meerdere leden melden mij dat ze bij het invoeren van een transactie een foutmelding krijgen (500: internal server error)
De transactie wordt (meestal?) correct uitgevoerd, maar nog de gevende, nog de ontvangende partij lijkt een bevestiging te ontvangen, waardoor regelmatig transacties meerdere keren worden uitgevoerd.

**Comment by eeemarv** [comment]
Ok, ik kijk ernaar

**Comment by eeemarv** [comment]
Vond deze fout vandaag nog plaats? Ik zie een aantal dubbele transacties op 28 juli. Sindsdien is er heel wat code veranderd. Dan kan het samenhangen met de fout die je eerder meldde ( #241 ). Ik probeerde net een aantal transacties in de test-installatie ( https://letsa.net/a/login in een gewoon leden-account) en ondervond geen fouten.

**Comment by AnneTanne** [comment]
Maarten,

Ik begreep dat Carine Bens (LZ027) inderdaad vandaag  nog problemen had.
Nadat ik een week geleden voor het eerst melding kreeg van dit probleem
(door Carla-Jo Van Geel), heb ik het zelf ook uitgetest, maar kon het niet
reproduceren.
En derde melding kwam inderdaad op 28 juli.
Maar bij Carine Bens was het zeker later. Ik informeer bij haar of het
inderdaad vandaag was.

Vriendelijke groet,
Ann Van Roy

**Comment by AnneTanne** [comment]
Maarten,
De transactie die een foutmelding had bij Carine Bens was inderdaad een
transactie van gisteren, zaterdag.

Vriendelijke groet,
Ann Van Roy

**Comment by eeemarv** [comment]
Ok. Ik vermoed dat het iets met de automatische minimum limiet te maken heeft. Wat zou verklaren waarom het maar bij sommige transacties optreedt. Ik bekijk het verder.

**Comment by eeemarv** [comment]
Ik denk dat het nu opgelost is. Inderdaad een fout in de automatische limiet. 

Zijdelingse opmerking: in jullie automatische limiet configuratie staan een heleboel accounts bij "exclusief". In feite is dit niet nodig. De automatische minimum limiet service is alleen van toepassing voor accounts die:

-  Alleen voor accounts die een individuele minimum limiet hebben. Als je de inidividuele minimum limieten wist, dan geldt de algemene minimum systeemslimiet (-3000 bij jullie) voor die accounts (dit kan in bulk op de "leden" pagina). Hoe meer individuele limieten je kan wissen, hoe handiger (minder te onderhouden data).
- Alleen accounts die een hogere individuele minimim limiet hebben dan de algemene minimimum systeemslimiet. Dus, bij een account met een individuele minimum limiet van -1000 zal die verlagen bij een ontvangen transactie, maar bij een account met een individuele minimum limiet van -4000 (lager dan de algemene minimum limiet van -3000) gebeurt er niets. 

De werkwijze die wij in onze groep toepassen: Alle indiviuele minimum en maximum limieten zijn gewist, behalve bij "instappers" die een bescheidene individuele minimum limiet krijgen die door de automatische minimum limiet service zal afnemen en uiteindelijk automatisch gewist worden (en dan is de algemene minimum limiet van toepassing). Daarbuiten zijn er enkele speciale accounts die een lagere individuele minimum en hogere maximum limiet krijgen, het secretariaat en interSysteem accounts.

Het veld "exclusief" in de configuratie staat er alleen om compleet te zijn, maar zelf kan ik geen situatie van toepassing indenken. (Het staat je vrij om het te gebruiken, natuurlijk).

**Comment by eeemarv** [comment]
@AnneTanne  Ik heb de namen de personen uit je comments vervangen door account-codes i.v.m. privacy.
