### ISSUE TITLE
systeem verstuurd geen mails naar nieuw lid met kloppen mailadres

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#257]
In LETS Zandland werd een nieuw lid ingevoerd met als mailadres [ email adres verwijderd: privacy en veiligheid]
Wanneer ik echter een welkomstmail wil versturen via eLAND, krijg ik een foutmelding dat naar de betrokken gebruiker geen mail kan worden verstuurd wegens ontbreken van emailadres.

**Comment by eeemarv** [comment]
Ok, ik bekijk het

**Comment by eeemarv** [comment]
Je bedoelt eigenlijk dat de fout optrad in de ledenpagina, de bulkmail. Want de "activatiemail" met paswoord is wel verstuurd zie ik. Daarna heb je proberen een mail te versturen via de bulkmail. Zo zie ik in de logs.

**Comment by AnneTanne** [comment]
Klopt

**Comment by eeemarv** [comment]
Het zou nu terug in orde moeten zijn. Dit weekend is de database abstractie laag geupdate en er waren wat foutjes ingekropen.
