### ISSUE TITLE
wachtwoord autogeneratie

### ISSUE THREAD

**Issue by retmarut** [eeemarv/eland#29]
http://site/users.php?pw=9876&r=admin&u=94949
Graag meer dan 7 karakters. Doe maar 15 of zo.

**Comment by eeemarv** [comment]
Misschien als configuratie, maar zeker niet standaard. 8 à 10 tekens (nu) is al een sterk wachtwoord en is te onthouden.

**Comment by dimitrydhondt** [comment]
Ik zou niet overdrijven met paswoorden. We spreken over een beperkte gemeenschapsmunt, die draait vooral op vertrouwen. We bouwen geen banking software...

Er is een punt waar de drang naar security en lange paswoorden de basis use-case in het gedrang brengt :-) (Zoals : alle gebruikers kunnen nog inloggen ;-))

Ik heb de overdreven en vertekende opvattingen over security bij eLAS/Taurix altijd al problematisch gevonden. Bvb. alles op moest per se achter 3 firewalls staan (die iemand "zelf" ging configureren !), maar samen met het feit dat andere evidente SQL injection attacks dan weer wel ongemoeid gelaten werden... Brrr.. 

Allez, in 't kort : Ik denk dat security in het algemeen een kwestie van balans/voldoende drempel is. En zeker nooit een absolute zaak.

**Comment by eeemarv** [comment]
Ik ben het eens met het gemeenschapsmunt argument. Dus, liever niet.

**Comment by eeemarv** [comment]
Huidige automatische wachtwoord generatie wordt als voldoende sterk beschouwd.
