### ISSUE TITLE
stop met html frame-sets

### ISSUE THREAD

**Issue by retmarut** [eeemarv/eland#30]
page-end scroll op brengt met tot:

"
eLAND  web app voor letsgroepen

Rapporteer bugs in de Github issue tracker. (Maak eerst een Github account aan.)
"
Frame-sets waren al niet graag gezien in de 90's. knip die footer weg is mijn devies. Mover de uitleg naar http://las.letsa.net/help.php

**Comment by eeemarv** [comment]
`<frame>` en `<frameset>` bestaan niet meer in HTML5, welke eLAND gebruikt. Het is een `<footer>`.

**Comment by eeemarv** [comment]
Menu en content hebben geen aparte scroll meer.
