### ISSUE TITLE
Request: Extra tabs voor aanbod/vraag

### ISSUE THREAD

**Issue by LetsSint-Niklaas** [eeemarv/eland#44]
LSN243 commented:
mag ik nog een tip geven? kan aanbod en vraag in aparte onderverdeling aub?
maakt het makkelijker wanneer je zelf iets wil zoeken... nu moet je doorheen de hele massa scrollen... 
ik zou het zetten als apart tabblad naast "Alle" , "aanbod" en "vraag"
je kan alleen sorteren wanner je op "lijst" klikt.

**Comment by eeemarv** [comment]
Hallo,
binnenkort komen er extra mogelijkheden om de overzichtspagina van vraag en aanbod te filteren. Eén van de mogelijkheden zal zijn dat je enkel de vragen of de aanbiedingen selecteerd. 
De extra filtermogelijkheden komen niet onder een tab. Feitelijk zijn er al te veel tabs zodat ze op de smartphone niet goed worden weergegeven. 
De filtermogelijkheden komen in een uitklapbaar paneel.
