### ISSUE TITLE
Probleem om bulk mail te versturen

### ISSUE THREAD

**Issue by LetsSint-Niklaas** [eeemarv/eland#47]
Desktopcomputer met Windows (7 home premium) en firefox.
Als ik probeer om een bulk mail te versturen krijg ik bij het klikken op de knop linksboven in mijn scherm een klein vensterstje dat zegt: selecteer een van volgende opties. Welke opties er zijn, heb ik het raden naar, want als ik er met de muis op klik, of zelfs maar scroll in het venster, verdwijnt dit weer.
Bulk mail is niet verzonden.
Als ik dit probeer in Chrome lukt het ook niet: de knop verandert van kleur, maar ik krijg verder geen respons.
Van beide acties is niets terug te vinden in de log.

**Comment by eeemarv** [comment]
Dit zou nu terug moeten werken.
