### ISSUE TITLE
Verwijderen overzichts- / indexpagina ?

### ISSUE THREAD

**Issue by eeemarv** [eeemarv/eland#53]
De overzichtspagina lijkt me weinig toegevoegde waarde te hebben. Zou het niet helderder zijn deze pagina te verwijderen en standaard gebruikers naar  'Vraag en aanbod' sturen na inloggen? Wat denken jullie?

**Comment by wiliv** [comment]
Inderdaad. Want nu zie je op de overzichtpagina vooral nieuwe leden, so what... En dat nieuw lijkt nogal relatief. Vraag en aanbod is het belangrijkste om zoveel mogelijk de aandacht op te vestigen.
