### ISSUE TITLE
Categorieën optioneel

### ISSUE THREAD

**Issue by eeemarv** [eeemarv/eland#75]
Momenteel zijn de categorieën van vraag en aanbod verplicht. 
Groepen zouden ervoor moeten kunnen kiezen met een extra instelling om categorieën niet te gebruiken of niet verplicht.

**Comment by AnneTanne** [comment]
Ik begrijp dat het optioneel maken van die categorieën inhoudt, dat de admin kan kiezen of categorieën wel of niet gebruikt worden, en indien wel, of dat al dan niet verplicht is.
Voor wat grotere groepen vind ik het namelijk inderdaad zinvol dat het verplicht is.
Ik merk dat onze leden sinds de overstap naar eLAND veel vaker dan voorheen nieuw aanbod invoeren.  En bij een paar honderd categorie-loze items, die dan in een standaardcategorie, bv 'Varia' terechtkomen, is het onmogelijk zoeken...  Dus ik wil dit graag verplicht laten!

Ik denk wel dat een groep die klein start en begint zonder categorieën, daar op een bepaald moment wel behoefte aan kan krijgen, en dan voor de taak staat een al relatief groot aanbod plots in categorieën te moeten verdelen zonder dat daar een basisstructuur voor is, en die dan 'from scratch' moet gaan verzinnen.
Wellicht in de toekomst een 'basisstructuur' aan categorieën voorzien, die vervolgens natuurlijk als vanouds aanpasbaar is?

**Comment by eeemarv** [comment]
Misschien kunnen groepen voor een basisstructuur te rade gaan bij andere groepen?
