### ISSUE TITLE
Case-sensitivity van gebruikersnaam

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#87]
Hoewel een wachtwoord natuurlijk hoofdlettergevoelig is, is een gebruikersnaam dat in de heel veel gevallen niet.  Ik krijg dan ook heel veel vragen van leden die met hoofdletters in hun mailadres (of kleine letters in hun code-suffix) proberen in te loggen, en 'niet herkend' worden...
Is het een overweging om de gebruikersnaam case-insensitive te maken?

**Comment by eeemarv** [comment]
Ok, de login is nu hoofdletterongevoelig.
