### ISSUE TITLE
Sorteren onderdelen overzichtsmail.

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#91]
We zouden graag vraag- en aanbod van interletsgroepen blijven zien in onze overzichtsmail, maar op dit ogenblik zorgt deze lange lijst ervoor, dat 'nieuws' en 'documenten' erg ver naar achter komen.
Voor onze groep zou prettig zijn, als we eerst eigen Vraag en Aanbod, dan Nieuws, vervolgens Documenten en Nieuwe leden, en pas helemaal op het einde Vraag en Aanbod van andere groepen zouden zien.

**Comment by eeemarv** [comment]
Wel daar moet ik eens over nadenken. Je kan in ieder geval al bepalen wat er bovenaan staat in de overzichtsmail. ("vraag en aabod" of "nieuws") Zie admin > instellingen > overzichtsmail > template

**Comment by eeemarv** [comment]
Dit is nu geïmplementeerd in de code maar moet nog getest worden.

**Comment by AnneTanne** [comment]
Geen enkel probleem met Firefox (iOS), maar met Chrome zijn de blokken niet groen en rood gekleurd zoals in FF, en ze zijn niet verplaatsbaar.  (Ook met Safari geen probleem)

**Comment by eeemarv** [comment]
Bij mij is er geen probleem met Chrome of Chromium. Is er een foutmelding in de javascript console? ( Tools > javascript console)  Gebruik je een muis of touchpad?  Een touchscreen zal niet werken, dat is een beperking van de gebruikte library. Wat is de versie van Chrome? (type chrome://version in de adresbalk) De mijne is 60.0

**Comment by eeemarv** [comment]
Op mijn Android phone schijnt verslepen met touchscreen toch te werken (Chromium-based Samsung browser). Dat de blokken ongekleurt zijn bij u zal te maken hebben met het feit dat de browser een oudere versie van de stylesheet gecached heeft. Ik ben vergeten een vernieuwing van de stylesheet te forceren maar zal dit nu doen.

**Comment by AnneTanne** [comment]
Ik vergiste me, het ging om Chrome voor OSX, niet voor iOS.
Maar hoewel gisteravond en vanmorgen ik het probleem in kwestie had, is het
nu in orde...
De javascript-console geeft weliswaar nog volgende foutmelding

config.php:1 Error in event handler for (unknown): SyntaxError: Unexpected
token u in JSON at position 0
    at
chrome-extension://boamfheepdiallipiieadpmnklbhadhc/hotkeyListener.js:1:80

Chrome Versie 60.0.3112.90

Vriendelijke groeten,
Ann


mailto:ann.van.roy@annetanne.be
http://annetanne.be

2017-08-14 9:01 GMT+02:00 martti <notifications@github.com>:

**Comment by eeemarv** [comment]
Ok. Wees voorzichtig met replying per mail op issues, je email address staat in de footer en wordt zo online gepubliceerd. Niet zo goed voor spam. Ik heb je mailadres inmiddels verwijderd.
