### ISSUE TITLE
aanbiedingen markeren als favoriet

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#92]
Vraag vanwege lid LETS Zandland:
Sommige aanbiedingen zijn 'interessant om te onthouden', maar niet acuut 'nodig'.  Bv iemand biedt een bep. dienst aan, die je in de toekomst wel nodig zou kunnen hebben, of heeft iets te lets-leen dat je over een half jaar waarschijnlijk wel eens wil gebruiken.
Vermits niet iedereen de categorieën even nauwkeurig toepast, is terugzoeken van die aanbiedingen in een grote LETS-groep wel eens lastig. 
Het zou interessant zijn, als een LETSer een aanbod van een groepsgenoot kon markeren (voor persoonlijk gebruik) om dit later snel terug te vinden.
Haalbaar???

**Comment by eeemarv** [comment]
Dat is wel haalbaar om te maken, maar feitelijk is deze al beschikbaar in je  browser in de vorm van de "favorieten".

**Comment by eeemarv** [comment]
Aangezien de functionaliteit al in de browser zit, wordt deze issue gesloten.
