### ISSUE TITLE
'nieuws' sorteren in omgekeerde volgorde?

### ISSUE THREAD

**Issue by AnneTanne** [eeemarv/eland#99]
Op dit ogenblik staat het nieuwsbericht (= evenement) het verst in de toekomst bovenaan, en moeten leden voor evenementen die kortbij zijn helemaal naar beneden scrollen.
Het zou fijn zijn als de admin een keuze kan maken om te sorteren in de omgekeerde richting.
Op die manier blijven (belangrijke) berichten met een datum in het verleden bovenaan staan (berichten die bewaard moeten blijven na datum), en zijn ook de evenementen in de onmiddelijke toekomst snel in beeld...

**Comment by eeemarv** [comment]
Zie Admin > Instellingen > Nieuws
Groetjes, m
